---
title: "Research"
date: '2023-05-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Select Publications 

#### Gender-Based Violence

* #MeToo in South Korea: Public Health Meets a Global Movement | [PubMed](https://pubmed.ncbi.nlm.nih.gov/35862888/)
* Sexual Violence and Mental Health Among College Students in the Era of #MeToo | [ResearchGate](https://www.researchgate.net/publication/345702710_Sexual_Violence_and_Mental_Health_Among_College_Students_in_the_Era_of_MeToo)

#### COVID-19

* Rapid Scaling Up of Telehealth Treatment for Tobacco-Dependent Cancer Patients During the COVID-19 Outbreak in New York City
 | [ResearchGate](https://www.researchgate.net/publication/342854047_Rapid_Scaling_Up_of_Telehealth_Treatment_for_Tobacco-Dependent_Cancer_Patients_During_the_COVID-19_Outbreak_in_New_York_City)
* The first 20 months of the COVID-19 pandemic: Mortality, intubation and ICU rates among 104,590 patients hospitalized at 21 United States health systems | [PubMed](https://pubmed.ncbi.nlm.nih.gov/36170336/)
* Relations of Current and Past Cancer with Severe Outcomes among 104,590 Hospitalized COVID-19 Patients: The COVID EHR Cohort at the University of Wisconsin | [ResearchGate](https://www.researchgate.net/publication/362717637_Relations_of_Current_and_Past_Cancer_with_Severe_Outcomes_among_104590_Hospitalized_COVID-19_Patients_The_COVID_EHR_Cohort_at_the_University_of_Wisconsin)
* Smoking Status, Nicotine Medication, Vaccination, and COVID-19 Hospital Outcomes: Findings from the COVID EHR Cohort at the University of Wisconsin (CEC-UW) Study | [ResearchGate](https://www.researchgate.net/publication/363361565_Smoking_Status_Nicotine_Medication_Vaccination_and_COVID-19_Hospital_Outcomes_Findings_from_the_COVID_EHR_Cohort_at_the_University_of_Wisconsin_CEC-UW_Study)

#### Hematology

* Quantitative Cytogenetic Analysis with karyoParser Allows for More Precise Identification of Disease Biology, Clonal Evolution, and Etiology of Relapse in Acute Myeloid Leukemia | [ResearchGate](https://www.researchgate.net/publication/365816951_Quantitative_Cytogenetic_Analysis_with_karyoParser_Allows_for_More_Precise_Identification_of_Disease_Biology_Clonal_Evolution_and_Etiology_of_Relapse_in_Acute_Myeloid_Leukemia)
* Wearable sensor-based performance status assessment in cancer: A pilot multicenter study from the Alliance for Clinical Trials in Oncology (A19_Pilot2) | [PubMed](https://pubmed.ncbi.nlm.nih.gov/36812616/) | [R Package](https://github.com/JLGlass/fitness) | [R Code](https://github.com/JLGlass/fitness_analysis_code)
* Single Cell ATAC Lineage Deconvolution Reveals Overlapping Subclones in Epigenetically Distinct AML Samples | [ResearchGate](https://www.researchgate.net/publication/356494698_Single_Cell_ATAC_Lineage_Deconvolution_Reveals_Overlapping_Subclones_in_Epigenetically_Distinct_AML_Samples)

### Academic Projects 

#### Data Science, Master of Science 

* Predicting Progression of Endometrial Cancer | [nbViewer](https://nbviewer.org/github/deepssquared/CUNY.MDS/blob/main/DATA602/DATA%20602%20FINAL.ipynb) | [Markdown](https://github.com/deepssquared/CUNY.MDS/blob/main/DATA602/DATA%20602%20FINAL.ipynb)
* COVID-19 Vaccine Clinic Simulation | [nbViewer](https://nbviewer.org/github/deepssquared/CUNY.MDS/blob/main/DATA604/FINAL/FINAL_SUBMISSION.ipynb) | [Markdown](https://github.com/deepssquared/CUNY.MDS/blob/main/DATA604/FINAL/FINAL_SUBMISSION.ipynb)
* The opioid epidemic in surveillance & survey data | [Markdown](https://rpubs.com/ddilip94/DATA607FINAL)

#### Epidemiology, Master of Public Health

* The Impact of Caste on Health | [Markdown](https://github.com/deepssquared/caste-health-india) | [GitHub Page](https://deepssquared.github.io/caste-health-india/)
*  Predicting Gender from Risk-Seeking Behaviors | [Markdown](https://github.com/deepssquared/DSII_FinalProject) | [GitHub Page](https://htmlpreview.github.io/?https://github.com/deepssquared/DSII_FinalProject/blob/master/final_report.html)

#### Miscellaneous Projects

* Death Rates and US Presidential Voting | [PubMed](https://pubmed.ncbi.nlm.nih.gov/31898122/)
